apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qx2n35sxk-go
  janus-idp.io/tekton: qx2n35sxk-go
  backstage.io/kubernetes-id: qx2n35sxk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qx2n35sxk-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
